name: otclim
channels:
  - conda-forge
dependencies:
  - mamba
  - python=3.11.8  # for 3.11.9 and later, dask has issue https://github.com/dask/dask/issues/11038
  - jupyterlab
  - scipy=1.11
  - numpy=1.24
  - numba=0.57
  - dask=2023.10  # would need to be upgraded to make it work with 3.11.9. Keep for now.
  - xarray=2023.10
  - h5netcdf=1.3
  - netcdf4=1.6
  - matplotlib=3.8
  - imageio=2.34
  - seaborn
  - plotly
  - jinja2=3.1
  - flaml=2.1
  - scikit-learn=1.3
  - joblib=1.3
  - lz4=4.3
  - pydantic=2.4
  - isodate=0.6.1
  - pytest=7.4
  - xgboost=2.0
  - lightgbm=4.3
  - catboost=1.2
  - shap=0.44
  - pip
  - pip:
      - cdsapi==0.7.*
      - fasttreeshap==0.1.*
